# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  github-damonto:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.SIGMO_PRO_MODULE_TOKEN}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/web" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/pro"
    registries:
      - github-damonto
    schedule:
      interval: "weekly"
    groups:
      gomod-dependencies:
        group-by: dependency-name
