services:
  sigmo:
    image: damonto/sigmo:latest
    container_name: sigmo
    restart: unless-stopped
    network_mode: host
    privileged: true
    tmpfs:
      - /run
    volumes:
      - ./config.toml:/app/config.toml
      - /dev:/dev
      - /run/udev:/run/udev:ro
      - /sys:/sys:ro
